#!/usr/bin/env bash
# generate.sh — render site/apps.html, a static no-JavaScript list of the apps in
# site/catalog.json (index.html builds the same list at page load).
#   site/generate.sh [catalog.json] [apps.html]
# Needs jq and bash. The Pages workflow runs it on every deploy, so apps.html is never
# committed; run it locally to preview.
set -euo pipefail
cd "$(dirname "$0")"
catalog="${1:-catalog.json}"
out="${2:-apps.html}"
command -v jq >/dev/null || { echo "generate.sh: jq is required (brew install jq)" >&2; exit 1; }
jq -e '.schemaVersion == 1 and (.apps | type == "array")' "$catalog" >/dev/null \
  || { echo "generate.sh: $catalog is not a schemaVersion 1 catalog" >&2; exit 1; }

jq -r '
  def esc: tostring | gsub("&"; "&amp;") | gsub("<"; "&lt;") | gsub(">"; "&gt;") | gsub("\""; "&quot;");
  def mb: if (type == "number" and . > 0) then ((. / 1048576 * 10 | round) / 10 | tostring) + " MB" else empty end;
  def page:
    if ((.homepage // "") | test("^https://github\\.com/[^/]+/[^/]+/?$")) then (.homepage | sub("/$"; "")) + "/releases/latest"
    elif .repo then "https://github.com/" + (if (.repo | contains("/")) then "" else "jamesrisberg/" end) + .repo + "/releases/latest"
    else (.homepage // "https://github.com/jamesrisberg/machud/releases/latest") end;
  def kind: {"windowed": "Window", "hover": "Hover panel", "umbrella": "Umbrella"}[.kind] // (.kind // "app");
  def meta: [("v" + (.version | tostring)), (.size | mb), (if .minOS then "macOS \(.minOS)+" else empty end)] | join(" · ");
  def card:
    "  <article class=\"card\" id=\"app-\(.id | esc)\">\n" +
    "    <div class=\"head\"><span class=\"mono\" aria-hidden=\"true\">\(.name[0:1] | ascii_upcase | esc)</span><div>" +
    "<h3>\(.name | esc)<span class=\"badge\">\(kind | esc)</span>" +
    (if .bundled then "<span class=\"badge bundled\">bundled</span>" else "" end) + "</h3>" +
    "<div class=\"meta\">\(meta | esc)</div></div></div>\n" +
    "    <p>\(.summary // "" | esc)</p>\n" +
    "    <div class=\"foot\"><a class=\"meta\" href=\"\(page | esc)\">Release notes</a>" +
    (if .download then "<a class=\"btn small primary\" href=\"\(.download | esc)\">Download</a>"
     else "<a class=\"btn small\" href=\"\(page | esc)\">Releases</a>" end) + "</div>\n  </article>";
  (.apps | map(select(.kind == "umbrella")) | first) as $m
  | (.apps | map(select(.kind != "umbrella")) | sort_by([(if .bundled then 0 else 1 end), (.name | ascii_downcase)])) as $tools
  | "<!doctype html>
<html lang=\"en\">
<head>
<meta charset=\"utf-8\">
<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
<title>MacHUD apps</title>
<link rel=\"stylesheet\" href=\"style.css\">
</head>
<body>
<!-- Generated by site/generate.sh from catalog.json; do not edit by hand. -->
<header class=\"top\"><div class=\"wrap\"><a class=\"brand\" href=\"index.html\"><span class=\"mono\">M</span>MacHUD</a>
<nav class=\"links\"><a href=\"index.html\">Home</a><a href=\"https://github.com/jamesrisberg/machud\">GitHub</a></nav></div></header>
<main>
<section id=\"apps\" style=\"border-top:0\"><div class=\"wrap\">
<h2>MacHUD and its apps</h2>
<p class=\"lede\">" +
    (if $m then "<a class=\"btn primary\" href=\"\(($m.download // ($m | page)) | esc)\">Download MacHUD \($m.version | esc)</a> <span class=\"meta\">\($m | meta | esc)</span>"
     else "<a class=\"btn primary\" href=\"https://github.com/jamesrisberg/machud/releases/latest\">Download MacHUD</a>" end) +
    "</p>
<div class=\"grid-apps\">
" + (if ($tools | length) == 0 then "  <div class=\"empty\">No apps have been published yet.</div>" else ($tools | map(card) | join("\n")) end) + "
</div>
</div></section>
</main>
<footer><div class=\"wrap\"><span>Catalog updated \(.updatedAt // "unknown" | esc) · <a href=\"catalog.json\">catalog.json</a></span></div></footer>
</body>
</html>"
' "$catalog" > "$out.tmp"
mv "$out.tmp" "$out"
echo >&2 "generate.sh: wrote $out ($(jq '.apps | length' "$catalog") catalog entries)"
